In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [51]:
dataset = pd.read_csv('winequality-red.csv')

In [52]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [53]:
df = pd.DataFrame(dataset)

In [54]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df['fixed acidity'] = sc.fit_transform(df[['fixed acidity']])
df['volatile acidity'] = sc.fit_transform(df[['volatile acidity']])
df['citric acid'] = sc.fit_transform(df[['citric acid']])
df['residual sugar'] = sc.fit_transform(df[['residual sugar']])
df['chlorides'] = sc.fit_transform(df[['chlorides']])
df['free sulfur dioxide'] = sc.fit_transform(df[['free sulfur dioxide']])
df['total sulfur dioxide'] = sc.fit_transform(df[['total sulfur dioxide']])
df['density'] = sc.fit_transform(df[['density']])
df['pH'] = sc.fit_transform(df[['pH']])
df['sulphates'] = sc.fit_transform(df[['sulphates']])
df['alcohol'] = sc.fit_transform(df[['alcohol']])


In [55]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
1         -0.298547          1.967442    -1.391472        0.043416   0.223875   
2         -0.298547          1.297065    -1.186070       -0.169427   0.096353   
3          1.654856         -1.384443     1.484154       -0.453218  -0.264960   
4         -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
...             ...               ...          ...             ...        ...   
1594      -1.217796          0.403229    -0.980669       -0.382271   0.053845   
1595      -1.390155          0.123905    -0.877968       -0.240375  -0.541259   
1596      -1.160343         -0.099554    -0.723916       -0.169427  -0.243707   
1597      -1.390155          0.654620    -0.775267       -0.382271  -0.264960   
1598      -1.332702         -1.216849     1.021999        0.752894  -0.434990   

      free sulfur dioxide  total sulfur dioxide   density        pH  \
0               -0.466193             -0.379133  0.558274  1.288643   
1                0.872638              0.624363  0.028261 -0.719933   
2               -0.083669              0.229047  0.134264 -0.331177   
3                0.107592              0.411500  0.664277 -0.979104   
4               -0.466193             -0.379133  0.558274  1.288643   
...                   ...                   ...       ...       ...   
1594             1.542054             -0.075043 -0.978765  0.899886   
1595             2.211469              0.137820 -0.862162  1.353436   
1596             1.255161             -0.196679 -0.533554  0.705508   
1597             1.542054             -0.075043 -0.676657  1.677400   
1598             0.203223             -0.135861 -0.666057  0.511130   

      sulphates   alcohol  quality  
0     -0.579207 -0.960246        5  
1      0.128950 -0.584777        5  
2     -0.048089 -0.584777        5  
3     -0.461180 -0.584777        6  
4     -0.579207 -0.960246        5  
...         ...       ...      ...  
1594  -0.461180  0.072294        5  
1595   0.601055  0.729364        6  
1596   0.542042  0.541630        6  
1597   0.305990 -0.209308        5  
1598   0.010924  0.541630        6  

[1599 rows x 12 columns]

In [56]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [57]:
X[0]

array([-1.,  1., -1., -0., -0., -0., -0.,  1.,  1., -1., -1.])

In [58]:
y[0]

5

In [113]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [114]:
X_train[0]

array([-1., -1., -0., -0., -0.,  2.,  1., -0.,  1., -0., -0.])

In [115]:
y_train[0]

5

In [116]:
X_test[0]

array([ 0., -1.,  2., -0.,  0., -1., -0.,  1.,  1.,  0.,  0.])

In [117]:
y_test[0]

5

In [134]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [135]:
y_pred = regressor.predict(X_test)

In [136]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=0)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[6. 5.]
 [5. 6.]
 [6. 6.]
 [6. 6.]
 [7. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 5.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [6. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 6.]
 [6. 7.]
 [5. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 7.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 5.]
 [5. 4.]
 [6. 7.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [6. 5.]
 [5. 5.]
 [6. 5.]
 [5. 6.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 6.]
 [7. 7.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [6. 6.]
 [6. 6.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [6. 5.]
 [6. 6.]
 [6. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [6. 5.]
 [5. 5.]
 [5. 5.]
 [6. 7.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [6. 7.]
 [5. 5.]
 [6. 6.]
 [6. 5.]
 [5. 5.]
 [6. 6.]
 [5. 5.]
 [5. 3.]
 [6. 6.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [5. 5.]
 [6. 6.]
 [5. 6.]
 [6. 5.]
 [6. 6.]
 [7. 7.]
 

In [137]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.3436370198437033

In [ ]:
# Linear Regression Accuraccy : 34.66%
# using some other regression models...
# Accuracy score i got..
# Support Vector : 33.45%
# Random Forest : 37.62%